### ISSUE TITLE
validation dataset clarification for evaluation

### ISSUE THREAD

**Issue by usama-ahmedkhan** [mit-han-lab/mcunet#2]
I am confused about the val dataset, is it image net-1000 classes or tiny-image net-200, also what is the input size of images trained is it 64x64 ?.

I tested the models and ran the script given in  eval on github page, my dataset is tiny-imagenet-200 dataset, the accuracy shown is very low.

**Comment by tonylins** [comment]
Hi, the dataset is the official ImageNet-1k dataset (ILSVRC2012). Since the memory is quite limited for MCUs, we used a small input image resolution, which is designed by the Neural Architecture Search process.
