### ISSUE TITLE
Training and testing on different datasets

### ISSUE THREAD

**Issue by usama-ahmedkhan** [mit-han-lab/mcunet#3]
Thanks for answering @tonylins  to my previous question, can you please tell if i had to test these mcunet models on tiny-image-net-200 dataset, where images are of size 64x64, can i directly use the trained models that are provided or i would have to train from scratch. 

The repo does not have training or testing on datasets other than used in paper. 

Also  ,i fed validation data of tiny-imagenet-200 to 512kb and other models, the accuracy was like almost zero, what could be the reason, because even the input resolution is 64x64 ,shouldn't there should be some accuracy, as the model is trained on imagenet-1000 classes dataset, it must have some accuracy on the same but low resolution data.

**Comment by tonylins** [comment]
Hi, I am not familiar with the tiny-image-net 200 dataset. My guess is that: firstly, if it only has 200 classes, the class index might not corresponds to the imagenet-1000 dataset (same label id refers to different categories); secondly, the image processing used to produce the 64x64 image is different from our augmentation.

**Comment by tonylins** [comment]
Close due to inactivity. Feel free to reopen.
