### ISSUE TITLE
the mcu side software paltform for deploy

### ISSUE THREAD

**Issue by WANGSSSSSSS** [mit-han-lab/mcunet#5]
Thanks for your great works, i am trying to deploy mcunet to stm32f746g-disco, so i want to know what software platform you use to generate the runtime code(tf-micro, tvm), or you just write it line by line?

**Comment by WANGSSSSSSS** [comment]
tf-micro, i find it.

**Comment by tonylins** [comment]
Thanks for your interest in the work. we will also release TinyEngine later this summer, which will provide a faster and more memory-efficient inference compared to tf-lite.
